### PR TITLE
Update to rustix 0.38 and update MSRV to 1.63

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by Stebalien** [comment]
Hm. This will move us from Debian bullseye (oldstable) to bookworm (just released stable). That's _probably_ fine given that everyone except the distro maintainers will be using rustup.

**Comment by Stebalien** [comment]
Could you update the readme? (right under the usage header)

**Comment by sdroege** [comment]
Sure, done! Sorry for the delay.

I also fixed the `cargo fmt` CI failure.

**Review by Stebalien — APPROVED** [review]

**Comment by Stebalien** [comment]
Thanks!

**Pull request merged**
