### PR TITLE
fix: drop redox_syscall dependency

### LINKED ISSUE #271: redox_syscall no longer appropriate?
> That said, redox_syscall is no longer meant to be used anywhere except for low-level userspace components like relibc and drivers, as Redox doesn't guarantee a stable syscall ABI. Instead, the libredox crate is recommended

This is from [the private Redox OS/Dev Matrix room](https://matrix.to/#/!lJMcRpoJcrWcQwuxoV:matrix.org/$k1e9lD6hfiwhNinTEq_71jWApcsv9u_PWF4vdApSQSE?via=matrix.org&via=mozilla.org).

### PR DESCRIPTION
**Pull request by Stebalien**
fixes #271

### CODE REVIEW

**Comment by mightyiam** [comment]
Thank you, @Stebalien. Sorry, I've never been involved in Redox OS development. I pointed the developers at this PR, asking for their help.

**Comment by jackpot51** [comment]
This looks correct to me.

**Comment by Stebalien** [comment]
Thanks!

**Comment by mightyiam** [comment]
Thank you.

**Pull request merged**
